import { db } from '@/lib/db'

// Catálogo completo de repuestos para electrodomésticos del hogar
const PARTS = [
  // ============== LAVADORAS ==============
  {
    sku: 'BMB-LAV-UNI01',
    name: 'Bomba de agua/drenaje universal',
    description: 'Bomba de desagüe universal para lavadoras automáticas 110V/220V',
    category: 'washing_machine',
    applianceType: 'Lavadora',
    brand: 'Universal',
    compatibleBrands: ['LG', 'Samsung', 'Whirlpool', 'Mabe', 'Haceb'],
    model: 'Universal',
    voltage: '110V/220V',
    powerWatts: '40W',
    dimensions: '12x10x8 cm',
    warranty: 6,
    stock: 6, minStock: 3, unitCost: 45000, unitPrice: 85000, location: 'Estante A-1',
  },
  {
    sku: 'CINT-LAV-UNI',
    name: 'Kit correas lavadora (set 3)',
    description: 'Set de 3 correas universales para lavadora automática (A, B, C)',
    category: 'washing_machine',
    applianceType: 'Lavadora',
    brand: 'Universal',
    compatibleBrands: ['LG', 'Samsung', 'Whirlpool', 'Mabe', 'Daewoo'],
    model: 'Universal',
    dimensions: '3 correas surtidas',
    warranty: 3,
    stock: 12, minStock: 4, unitCost: 18000, unitPrice: 42000, location: 'Estante A-2',
  },
  {
    sku: 'ROD-LAV-UNI',
    name: 'Rodamiento de tambor (par)',
    description: 'Par de rodamientos sellados para tambor de lavadora (6204-2RS + 6205-2RS)',
    category: 'washing_machine',
    applianceType: 'Lavadora',
    brand: 'Universal',
    compatibleBrands: ['LG', 'Samsung', 'Bosch', 'Electrolux'],
    model: '6204-2RS / 6205-2RS',
    dimensions: '47x20x14 mm / 52x15x15 mm',
    warranty: 12,
    stock: 4, minStock: 2, unitCost: 35000, unitPrice: 72000, location: 'Estante A-3',
  },
  {
    sku: 'CARB-LAV-UNI',
    name: 'Carbones de motor lavadora (par)',
    description: 'Carbones de carbón para motor de lavadora universal 5x8x12mm',
    category: 'washing_machine',
    applianceType: 'Lavadora',
    brand: 'Universal',
    compatibleBrands: ['LG', 'Samsung', 'Whirlpool', 'Mabe'],
    model: '5x8x12 mm',
    warranty: 6,
    stock: 10, minStock: 5, unitCost: 8000, unitPrice: 22000, location: 'Estante A-4',
  },
  {
    sku: 'ELEC-LAV-UNI',
    name: 'Electroválvula de entrada de agua',
    description: 'Electroválvula universal de 2 vías para entrada de agua fría/caliente 110V',
    category: 'washing_machine',
    applianceType: 'Lavadora',
    brand: 'Universal',
    compatibleBrands: ['LG', 'Samsung', 'Whirlpool', 'Mabe', 'Haceb'],
    voltage: '110V',
    dimensions: '8x6x5 cm',
    warranty: 6,
    stock: 5, minStock: 2, unitCost: 28000, unitPrice: 55000, location: 'Estante A-5',
  },

  // ============== NEVERAS ==============
  {
    sku: 'TERM-NEV-UNI',
    name: 'Termostato de nevera universal',
    description: 'Termostato mecánico universal para nevera/congelador rango -25°C a 10°C',
    category: 'refrigerator',
    applianceType: 'Nevera',
    brand: 'Universal',
    compatibleBrands: ['LG', 'Samsung', 'Whirlpool', 'Mabe', 'Haceb', 'Electrolux'],
    model: 'Universal',
    dimensions: 'Capilar 1.5m',
    warranty: 12,
    stock: 8, minStock: 3, unitCost: 25000, unitPrice: 55000, location: 'Estante B-1',
  },
  {
    sku: 'COMP-NEV-14',
    name: 'Compresor nevera 1/4 HP R134a',
    description: 'Compresor refrigerante 1/4 HP para nevera, gas R134a, 220V',
    category: 'refrigerator',
    applianceType: 'Nevera',
    brand: 'Universal',
    compatibleBrands: ['LG', 'Samsung', 'Whirlpool', 'Mabe'],
    model: 'R134a 1/4 HP',
    voltage: '220V',
    powerWatts: '180W',
    gasType: 'R134a',
    dimensions: '18x16x15 cm',
    warranty: 12,
    stock: 3, minStock: 2, unitCost: 280000, unitPrice: 450000, location: 'Estante B-2',
  },
  {
    sku: 'SELLO-NEV-UNI',
    name: 'Kit sello de puerta (magnético)',
    description: 'Kit universal de sello magnético para puerta de nevera, corte a medida',
    category: 'refrigerator',
    applianceType: 'Nevera',
    brand: 'Universal',
    compatibleBrands: ['LG', 'Samsung', 'Whirlpool', 'Mabe', 'Haceb'],
    model: 'Universal',
    dimensions: 'Rollo 3m',
    warranty: 6,
    stock: 6, minStock: 3, unitCost: 18000, unitPrice: 42000, location: 'Estante B-3',
  },
  {
    sku: 'RELEV-NEV-UNI',
    name: 'Relé PTC arraque compresor',
    description: 'Relé PTC universal para arranque de compresor de nevera 1/4 a 1/3 HP',
    category: 'refrigerator',
    applianceType: 'Nevera',
    brand: 'Universal',
    compatibleBrands: ['LG', 'Samsung', 'Whirlpool', 'Mabe', 'Electrolux'],
    voltage: '220V',
    warranty: 6,
    stock: 12, minStock: 4, unitCost: 12000, unitPrice: 32000, location: 'Estante B-4',
  },
  {
    sku: 'TERMER-NEV-UNI',
    name: 'Termómetro de nevera digital',
    description: 'Termómetro digital con sonda para nevera/congelador -40°C a 50°C',
    category: 'refrigerator',
    applianceType: 'Nevera',
    brand: 'Universal',
    dimensions: '5x3x1 cm',
    warranty: 6,
    stock: 8, minStock: 3, unitCost: 15000, unitPrice: 38000, location: 'Estante B-5',
  },

  // ============== CONGELADORE ==============
  {
    sku: 'TERM-CON-ADJ',
    name: 'Termostato ajustable congelador',
    description: 'Termostato ajustable para congelador horizontal/vertical -30°C a 0°C',
    category: 'freezer',
    applianceType: 'Congelador',
    brand: 'Universal',
    compatibleBrands: ['Haceb', 'Mabe', 'Whirlpool', 'LG'],
    model: 'Universal',
    dimensions: 'Capilar 2m',
    warranty: 12,
    stock: 4, minStock: 2, unitCost: 35000, unitPrice: 72000, location: 'Estante C-1',
  },
  {
    sku: 'COMP-CON-13',
    name: 'Compresor congelador 1/3 HP R404A',
    description: 'Compresor de baja temperatura 1/3 HP para congelador, gas R404A, 220V',
    category: 'freezer',
    applianceType: 'Congelador',
    brand: 'Universal',
    compatibleBrands: ['Haceb', 'Mabe', 'Whirlpool', 'Frigidaire'],
    model: 'R404A 1/3 HP',
    voltage: '220V',
    powerWatts: '250W',
    gasType: 'R404A',
    dimensions: '20x18x16 cm',
    warranty: 12,
    stock: 2, minStock: 2, unitCost: 420000, unitPrice: 650000, location: 'Estante C-2',
  },
  {
    sku: 'TIMER-CON-UNI',
    name: 'Timer de descongelamiento',
    description: 'Timer universal de descongelamiento para congelador 220V ciclo 8h',
    category: 'freezer',
    applianceType: 'Congelador',
    brand: 'Universal',
    compatibleBrands: ['Haceb', 'Mabe', 'Whirlpool', 'LG', 'Samsung'],
    voltage: '220V',
    warranty: 6,
    stock: 6, minStock: 3, unitCost: 22000, unitPrice: 48000, location: 'Estante C-3',
  },
  {
    sku: 'RESIS-CON-UNI',
    name: 'Resistencia descongeladora',
    description: 'Resistencia calefactora universal para descongelamiento de evaporador 150W',
    category: 'freezer',
    applianceType: 'Congelador',
    brand: 'Universal',
    compatibleBrands: ['Haceb', 'Mabe', 'Whirlpool', 'Frigidaire'],
    voltage: '220V',
    powerWatts: '150W',
    warranty: 6,
    stock: 5, minStock: 2, unitCost: 28000, unitPrice: 58000, location: 'Estante C-4',
  },

  // ============== SECADORAS A GAS ==============
  {
    sku: 'VAL-SEC-GAS-01',
    name: 'Válvula solenoide de gas',
    description: 'Válvula solenoide de gas para secadora 2 vías 110V/220V',
    category: 'gas_dryer',
    applianceType: 'Secadora a gas',
    brand: 'Universal',
    compatibleBrands: ['Whirlpool', 'Maytag', 'Kenmore', 'Frigidaire'],
    voltage: '110V/220V',
    dimensions: '10x8x6 cm',
    warranty: 12,
    stock: 2, minStock: 2, unitCost: 75000, unitPrice: 135000, location: 'Estante D-1',
  },
  {
    sku: 'ENC-SEC-GAS',
    name: 'Kit encendedor/piloto universal',
    description: 'Kit encendedor de gas con sensor de llama para secadora a gas',
    category: 'gas_dryer',
    applianceType: 'Secadora a gas',
    brand: 'Universal',
    compatibleBrands: ['Whirlpool', 'Maytag', 'Kenmore', 'Frigidaire', 'General Electric'],
    model: 'Universal',
    warranty: 6,
    stock: 5, minStock: 3, unitCost: 38000, unitPrice: 78000, location: 'Estante D-2',
  },
  {
    sku: 'TERM-SEC-GAS',
    name: 'Termostato de temperatura secadora',
    description: 'Termostato de alta temperatura para secadora a gas hasta 80°C',
    category: 'gas_dryer',
    applianceType: 'Secadora a gas',
    brand: 'Universal',
    compatibleBrands: ['Whirlpool', 'Maytag', 'Kenmore', 'Frigidaire'],
    warranty: 6,
    stock: 4, minStock: 2, unitCost: 25000, unitPrice: 55000, location: 'Estante D-3',
  },
  {
    sku: 'CORR-SEC-GAS',
    name: 'Correa de transmisión secadora',
    description: 'Correa de transmisión para secadora a gas 1925H7 universal',
    category: 'gas_dryer',
    applianceType: 'Secadora a gas',
    brand: 'Universal',
    compatibleBrands: ['Whirlpool', 'Maytag', 'Kenmore', 'Frigidaire'],
    model: '1925H7',
    dimensions: '1925 mm',
    warranty: 6,
    stock: 7, minStock: 3, unitCost: 22000, unitPrice: 48000, location: 'Estante D-4',
  },
  {
    sku: 'FLAM-SEC-GAS',
    name: 'Sensor de llama secadora',
    description: 'Sensor de llama para secadora a gas, detecta llama del piloto',
    category: 'gas_dryer',
    applianceType: 'Secadora a gas',
    brand: 'Universal',
    compatibleBrands: ['Whirlpool', 'Maytag', 'Kenmore'],
    warranty: 6,
    stock: 3, minStock: 2, unitCost: 32000, unitPrice: 68000, location: 'Estante D-5',
  },

  // ============== AIRES ACONDICIONADOS ==============
  {
    sku: 'CAP-AC-35',
    name: 'Capacitor AC 35µF 450V',
    description: 'Capacitor de arranque 35µF 450V para motor de aire acondicionado split',
    category: 'air_conditioner',
    applianceType: 'Aire acondicionado',
    brand: 'Universal',
    compatibleBrands: ['Midea', 'LG', 'Samsung', 'Daikin', 'Panasonic'],
    voltage: '450V',
    dimensions: '45x70 mm',
    warranty: 12,
    stock: 8, minStock: 3, unitCost: 22000, unitPrice: 55000, location: 'Estante E-1',
  },
  {
    sku: 'CAP-AC-50',
    name: 'Capacitor AC 50µF 450V',
    description: 'Capacitor de arranque 50µF 450V para compresor de AC 18.000-24.000 BTU',
    category: 'air_conditioner',
    applianceType: 'Aire acondicionado',
    brand: 'Universal',
    compatibleBrands: ['Midea', 'LG', 'Samsung', 'Daikin', 'Carrier'],
    voltage: '450V',
    dimensions: '50x90 mm',
    warranty: 12,
    stock: 5, minStock: 2, unitCost: 28000, unitPrice: 65000, location: 'Estante E-1',
  },
  {
    sku: 'MOT-AC-12K',
    name: 'Motor ventilador interior 12K BTU',
    description: 'Motor de ventilador para unidad interior de split 12.000 BTU 220V',
    category: 'air_conditioner',
    applianceType: 'Aire acondicionado',
    brand: 'Universal',
    compatibleBrands: ['Midea', 'LG', 'Samsung', 'Daikin'],
    voltage: '220V',
    powerWatts: '25W',
    warranty: 12,
    stock: 3, minStock: 2, unitCost: 95000, unitPrice: 165000, location: 'Estante E-2',
  },
  {
    sku: 'MOT-AC-EXT',
    name: 'Motor ventilador exterior',
    description: 'Motor de ventilador para unidad condensadora exterior 220V 6 polos',
    category: 'air_conditioner',
    applianceType: 'Aire acondicionado',
    brand: 'Universal',
    compatibleBrands: ['Midea', 'LG', 'Samsung', 'Daikin', 'Carrier'],
    voltage: '220V',
    powerWatts: '45W',
    warranty: 12,
    stock: 2, minStock: 2, unitCost: 125000, unitPrice: 215000, location: 'Estante E-3',
  },
  {
    sku: 'FILT-AC-12K',
    name: 'Filtro de aire AC 12K BTU',
    description: 'Filtro de aire lavable para unidad interior de split 12.000 BTU',
    category: 'air_conditioner',
    applianceType: 'Aire acondicionado',
    brand: 'Universal',
    compatibleBrands: ['Midea', 'LG', 'Samsung', 'Daikin'],
    dimensions: '32x12 cm',
    warranty: 3,
    stock: 10, minStock: 4, unitCost: 8000, unitPrice: 22000, location: 'Estante E-4',
  },
  {
    sku: 'PCB-AC-UNI',
    name: 'Tarjeta control universal AC',
    description: 'Tarjeta electrónica de control universal para AC split 220V con control remoto',
    category: 'air_conditioner',
    applianceType: 'Aire acondicionado',
    brand: 'Universal',
    compatibleBrands: ['Midea', 'LG', 'Samsung', 'Daikin', 'Carrier'],
    voltage: '220V',
    warranty: 6,
    stock: 2, minStock: 2, unitCost: 85000, unitPrice: 155000, location: 'Estante E-5',
  },

  // ============== TVs ==============
  {
    sku: 'PAN-TV-LED-55',
    name: 'Display LED TV 55" (tiras)',
    description: 'Kit de tiras LED retroiluminación para TV 55" universal 6 tiras',
    category: 'tv',
    applianceType: 'TV',
    brand: 'Universal',
    compatibleBrands: ['Sony', 'Samsung', 'LG', 'TCL', 'Sharp'],
    model: 'Universal 55"',
    voltage: '12V',
    dimensions: '55" 6 tiras',
    warranty: 6,
    stock: 1, minStock: 2, unitCost: 320000, unitPrice: 580000, location: 'Estante F-1',
  },
  {
    sku: 'PAN-TV-LED-43',
    name: 'Display LED TV 43" (tiras)',
    description: 'Kit de tiras LED retroiluminación para TV 43" universal 5 tiras',
    category: 'tv',
    applianceType: 'TV',
    brand: 'Universal',
    compatibleBrands: ['Sony', 'Samsung', 'LG', 'TCL', 'Sharp'],
    model: 'Universal 43"',
    voltage: '12V',
    dimensions: '43" 5 tiras',
    warranty: 6,
    stock: 3, minStock: 2, unitCost: 240000, unitPrice: 440000, location: 'Estante F-1',
  },
  {
    sku: 'FUENTE-TV-UNI',
    name: 'Fuente de poder TV universal',
    description: 'Fuente switching universal para TV LED 32"-55" 12V/24V multi-salida',
    category: 'tv',
    applianceType: 'TV',
    brand: 'Universal',
    compatibleBrands: ['Sony', 'Samsung', 'LG', 'TCL', 'Sharp', 'Toshiba'],
    voltage: '110V/220V entrada',
    powerWatts: '120W',
    warranty: 6,
    stock: 7, minStock: 3, unitCost: 48000, unitPrice: 95000, location: 'Estante F-2',
  },
  {
    sku: 'TCON-TV-UNI',
    name: 'Tarjeta T-CON TV universal',
    description: 'Tarjeta T-CON universal para TV LED 32"-55" compatible V-by-One/LVDS',
    category: 'tv',
    applianceType: 'TV',
    brand: 'Universal',
    compatibleBrands: ['Sony', 'Samsung', 'LG', 'TCL', 'Sharp'],
    voltage: '12V',
    warranty: 6,
    stock: 4, minStock: 2, unitCost: 55000, unitPrice: 115000, location: 'Estante F-3',
  },
  {
    sku: 'INV-TV-UNI',
    name: 'Inversor LED TV universal',
    description: 'Inversor universal para retroiluminación LED de TV 32"-55"',
    category: 'tv',
    applianceType: 'TV',
    brand: 'Universal',
    compatibleBrands: ['Sony', 'Samsung', 'LG', 'TCL', 'Sharp'],
    voltage: '12V/24V entrada',
    warranty: 6,
    stock: 5, minStock: 2, unitCost: 38000, unitPrice: 85000, location: 'Estante F-4',
  },
  {
    sku: 'CTRL-TV-UNI',
    name: 'Control remoto universal TV',
    description: 'Control remoto universal para TV con programación automática',
    category: 'tv',
    applianceType: 'TV',
    brand: 'Universal',
    compatibleBrands: ['Sony', 'Samsung', 'LG', 'TCL', 'Sharp', 'Toshiba', 'Panasonic'],
    warranty: 3,
    stock: 15, minStock: 5, unitCost: 8000, unitPrice: 25000, location: 'Estante F-5',
  },

  // ============== REFRIGERACIÓN (Gases y consumibles) ==============
  {
    sku: 'GAS-R134A-500',
    name: 'Gas refrigerante R134a 500g',
    description: 'Recarga de gas refrigerante R134a 500g con manómetro y manguera',
    category: 'refrigeration',
    applianceType: 'Nevera',
    brand: 'Universal',
    gasType: 'R134a',
    dimensions: 'Cilindro 500g',
    warranty: 0,
    unit: 'unidad',
    stock: 10, minStock: 4, unitCost: 65000, unitPrice: 120000, location: 'Estante G-1',
  },
  {
    sku: 'GAS-R410A-5K',
    name: 'Gas refrigerante R410A 5kg',
    description: 'Cilindro de gas R410A 5kg para aire acondicionado inverter',
    category: 'refrigeration',
    applianceType: 'Aire acondicionado',
    brand: 'Universal',
    gasType: 'R410A',
    dimensions: 'Cilindro 5kg',
    warranty: 0,
    stock: 3, minStock: 2, unitCost: 185000, unitPrice: 320000, location: 'Estante G-2',
  },
  {
    sku: 'GAS-R22-500',
    name: 'Gas refrigerante R22 500g',
    description: 'Recarga de gas R22 500g para AC antiguos (en desuso)',
    category: 'refrigeration',
    applianceType: 'Aire acondicionado',
    brand: 'Universal',
    gasType: 'R22',
    dimensions: 'Cilindro 500g',
    warranty: 0,
    stock: 2, minStock: 1, unitCost: 95000, unitPrice: 165000, location: 'Estante G-3',
  },
  {
    sku: 'ACEITE-POE-1L',
    name: 'Aceite POE lubricante 1L',
    description: 'Aceite lubricante POE para compresores de AC inverter 1 litro',
    category: 'refrigeration',
    applianceType: 'Aire acondicionado',
    brand: 'Universal',
    dimensions: '1 litro',
    unit: 'litro',
    warranty: 0,
    stock: 6, minStock: 2, unitCost: 35000, unitPrice: 72000, location: 'Estante G-4',
  },
  {
    sku: 'VACUO-BOMBA-OIL',
    name: 'Aceite para bomba de vacío 1L',
    description: 'Aceite mineral para bomba de vacío de servicio 1 litro',
    category: 'refrigeration',
    brand: 'Universal',
    dimensions: '1 litro',
    unit: 'litro',
    warranty: 0,
    stock: 4, minStock: 2, unitCost: 25000, unitPrice: 52000, location: 'Estante G-5',
  },
  {
    sku: 'SOLDADURA-PLATA',
    name: 'Varilla de soldadura plata (5u)',
    description: 'Varillas de soldadura de plata 5 unidades para tubería de cobre',
    category: 'refrigeration',
    brand: 'Universal',
    dimensions: '5 varillas 2mm',
    warranty: 0,
    stock: 8, minStock: 3, unitCost: 18000, unitPrice: 42000, location: 'Estante G-6',
  },

  // ============== HERRAMIENTAS ==============
  {
    sku: 'MAN-AC-SET',
    name: 'Manifold digital AC 4 válvulas',
    description: 'Manifold digital para servicio de AC con 4 válvulas y mangueras 72"',
    category: 'tools',
    brand: 'Universal',
    compatibleBrands: ['R134a', 'R410A', 'R22', 'R404A'],
    dimensions: 'Set completo',
    warranty: 12,
    stock: 1, minStock: 1, unitCost: 450000, unitPrice: 0, location: 'Herramientas H-1',
  },
  {
    sku: 'BOMBA-VACUO-2ET',
    name: 'Bomba de vacío 2 etapas',
    description: 'Bomba de vacío de 2 etapas 3.5 CFM para servicio de refrigeración',
    category: 'tools',
    brand: 'Universal',
    voltage: '110V',
    powerWatts: '250W',
    warranty: 12,
    stock: 1, minStock: 1, unitCost: 380000, unitPrice: 0, location: 'Herramientas H-2',
  },
  {
    sku: 'DET-FUGAS-ELEC',
    name: 'Detector de fugas electrónico',
    description: 'Detector electrónico de fugas de gas refrigerante con sensor',
    category: 'tools',
    brand: 'Universal',
    voltage: 'Pilas AA',
    warranty: 12,
    stock: 2, minStock: 1, unitCost: 180000, unitPrice: 0, location: 'Herramientas H-3',
  },
  {
    sku: 'DOB-TUBOS-COB',
    name: 'Dobladora de tubos de cobre',
    description: 'Dobladora manual de tubos de cobre 1/4" a 3/4"',
    category: 'tools',
    brand: 'Universal',
    dimensions: '1/4" a 3/4"',
    warranty: 24,
    stock: 3, minStock: 1, unitCost: 45000, unitPrice: 0, location: 'Herramientas H-4',
  },
  {
    sku: 'CORTE-TUBOS-PRO',
    name: 'Corta tubos profesional',
    description: 'Corta tubos de cobre profesional 3mm a 28mm con desbastador',
    category: 'tools',
    brand: 'Universal',
    dimensions: '3mm a 28mm',
    warranty: 24,
    stock: 4, minStock: 1, unitCost: 35000, unitPrice: 0, location: 'Herramientas H-5',
  },

  // ============== OTROS ==============
  {
    sku: 'CINTA-TEFLON',
    name: 'Cinta de teflón (rollo)',
    description: 'Cinta de teflón para sellado de roscas en conexiones de gas/agua',
    category: 'other',
    brand: 'Universal',
    dimensions: '12mm x 12m',
    unit: 'rollo',
    warranty: 0,
    stock: 20, minStock: 5, unitCost: 1500, unitPrice: 5000, location: 'Estante I-1',
  },
  {
    sku: 'GRASA-SILICONA',
    name: 'Grasa silicona 100g',
    description: 'Grasa de silicona dieléctrica para sellos y conexiones 100g',
    category: 'other',
    brand: 'Universal',
    dimensions: '100g',
    unit: 'gramo',
    warranty: 0,
    stock: 12, minStock: 3, unitCost: 8000, unitPrice: 22000, location: 'Estante I-2',
  },
  {
    sku: 'CABLE-COBRE-14',
    name: 'Cable de cobre 14AWG (metro)',
    description: 'Cable de cobre calibre 14 AWG para conexiones internas de electrodomésticos',
    category: 'other',
    brand: 'Universal',
    dimensions: '14 AWG',
    unit: 'metro',
    warranty: 0,
    stock: 50, minStock: 10, unitCost: 1200, unitPrice: 4500, location: 'Estante I-3',
  },
]

async function main() {
  console.log('🌱 Seeding catálogo de repuestos para electrodomésticos...')

  // Borrar repuestos existentes
  await db.inventoryMovement.deleteMany()
  await db.quoteItem.deleteMany()
  await db.part.deleteMany()

  let count = 0
  for (const p of PARTS) {
    await db.part.create({
      data: {
        ...p,
        compatibleBrands: p.compatibleBrands ? JSON.stringify(p.compatibleBrands) : null,
      },
    })
    count++

    // Crear movimiento de entrada inicial
    if (p.stock > 0) {
      await db.inventoryMovement.create({
        data: {
          partId: (await db.part.findUnique({ where: { sku: p.sku } }))!.id,
          movementType: 'in',
          quantity: p.stock,
          reason: 'Stock inicial',
          unitCost: p.unitCost,
        },
      })
    }
  }

  console.log(`✅ ${count} repuestos cargados`)

  // Contar por categoría
  const categories = await db.part.groupBy({
    by: ['category'],
    _count: { _all: true },
  })
  categories.forEach((c) => {
    console.log(`   - ${c.category}: ${c._count._all} repuestos`)
  })

  // Total valor inventario
  const parts = await db.part.findMany()
  const totalValue = parts.reduce((sum, p) => sum + p.stock * p.unitCost, 0)
  console.log(`   💰 Valor total inventario: $${new Intl.NumberFormat('es-CO').format(totalValue)}`)
}

main()
  .catch((e) => {
    console.error('❌ Error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
